from django.conf.urls import url
from goforward import views

urlpatterns = [
    url(r'^lion/$',
        views.LionQuizList.as_view(),
        name=views.LionQuizList.name),
    url(r'^lion/(?P<pk>[0-9]+)/$',
        views.LionQuizDetail.as_view(),
        name=views.LionQuizDetail.name),
    url(r'^four/$',
        views.FourQuizList.as_view(),
        name=views.FourQuizList.name),
    url(r'^four/(?P<pk>[0-9]+)/$',
        views.FourQuizDetail.as_view(),
        name=views.FourQuizDetail.name),
    url(r'^nine/$',
        views.NineQuizList.as_view(),
        name=views.NineQuizList.name),
    url(r'^nine/(?P<pk>[0-9]+)/$',
        views.NineQuizDetail.as_view(),
        name=views.NineQuizDetail.name),
    url(r'^random/$',
        views.RandomQuizList.as_view(),
        name=views.RandomQuizList.name),
    url(r'^random/(?P<pk>[0-9]+)/$',
        views.RandomQuizDetail.as_view(),
        name=views.RandomQuizDetail.name),
    url(r'^$',
        views.ApiRoot.as_view(),
        name=views.ApiRoot.name),
]
